### PR TITLE
Complete the build/mapping in a few seconds

### PR DESCRIPTION
**Pull request by rominf**
First off, thanks for taking the time to contribute!

## Please Complete the Following

- [x] I read `CONTRIBUTING.md`
- [x] I used tabs to indent
- [x] I have tested my change

## Notes

Mapping process execution on my laptop: 4.5 minutes -> 3.5 seconds.

Pipeline:
* Go compiler builds `build/mapping.go` into binary `build/mapping` with
  DuckDB embedded.
* `build/mapping` creates in-memory DuckDB database.
* DuckDB creates `skus` table based on input skus file.
* DuckDB reads mapping file which is stored in variable.
* DuckDB loads skus file into `skus` table.
* `build/mapping` performs update of `skus` table using varible with
  mapping.
* DuckDB dumps `skus` table back to skus file.

`skus.pl` was modified to fix encoding issues based on the StackOverflow
question: https://stackoverflow.com/a/30551086/2108548.

### CODE REVIEW

**Comment by Cyclenerd** [comment]
Thanks for the pull. Can you please use SQLite instead of DuckDB? SQLite can also store in memory and is already used in `pricing.pl` <https://github.com/Cyclenerd/google-cloud-pricing-cost-calculator/blob/master/build/pricing.pl#L126>

**Comment by rominf** [comment]
I know that SQLite can also work with in-memory databases (actually, it's the other way around: DuckDB learned on SQLite success). I used DuckDB because it supports direct CSV access via SQL (which is not true for SQLite). I can replace it with SQLite if you wish. Are you okay with the rest of the changes (like rewriting it to Go)?

**Comment by Cyclenerd** [comment]
Yes, I think your optimization is great. Thank you very much. If you implement it with SQLite I would appreciate it very much.

**Comment by rominf** [comment]
I wanted to avoid manual CSV reading (and defining a Go struct with 28 fields), so I implemented it with SQLite using https://github.com/ncruces/go-sqlite3 which includes an official CSV extension (not built into SQLite). Unfortunately, the official extension [doesn't support](https://www.sqlite.org/forum/info/b1d479097250d036) CSV files with separators different from `,`, so for testing, I changed the separator to `,` using LibreOffice Calc. Since `pricing.pl` also uses SQLite, I omitted conversion back to CSV in `mapping`. `mapping` executes significantly slower than with DuckDB, but still quite fast: less than 10 seconds on my laptop. `pricing.pl` is more compact now (no need to convert CSV to SQLite) and executes about 10 times faster mostly because I added missing index, but avoiding CSV helped as well. I expect CI build execution time to drop from 5 min 20 sec below 2 minutes.

I propose to avoid CSV for storing SKUs at all (generate SQLite DB in `skus.pl`) and replace the separator in `mapping.csv` from `;` to `,`. How does this sound to you?

**Comment by Cyclenerd** [comment]
That sounds wonderful. The CSVs should also be more of a temporary solution. But as always... Works and therefore not modified. You are welcome to rebuild everything.

**Comment by rominf** [comment]
I am closing this PR in favor of #120.

**Pull request closed without merging**
